#!/bin/bash

set -xeuo pipefail

REGISTRY=container-registry.dacodastrack.com
IMAGE_NAME_PREFIX=web-spherical-harmonics
BASE_IMAGE_NAME=$REGISTRY/$IMAGE_NAME_PREFIX-base
TEXTURE_GENERATOR_IMAGE_NAME=$REGISTRY/$IMAGE_NAME_PREFIX-texture-generator
FINAL_IMAGE_NAME=$REGISTRY/$IMAGE_NAME_PREFIX

: ${IMAGE_TAG:=latest}

base_work() {
	buildah run "$CONTAINER" sh <<"EOF"
apt-get update
apt-get install -y \
	g++ \
	make \
	pkg-config \
	libgsl-dev \
	libfcgi-dev \
	libmagickwand-dev \
	libmagickwand-6-headers \
	libltdl-dev \
	libx11-6 \
	liblcms2-dev \
	libxext-dev \
	libfreetype6-dev \
	libapache2-mod-fcgid
EOF
}

texture_generator_work() {
	buildah copy "$CONTAINER" src/texture-generator /usr/local/src/web-spherical-harmonics/texture-generator

	buildah run "$CONTAINER" sh <<"EOF"
mkdir -p /usr/local/apache2/fcgi-bin

make clean -C /usr/local/src/web-spherical-harmonics/texture-generator 
CXXFLAGS=-DUBUNTU make -C /usr/local/src/web-spherical-harmonics/texture-generator

cp /usr/local/src/web-spherical-harmonics/texture-generator/build/texture-generator \
       /usr/local/apache2/fcgi-bin/texture-generator \

chown -R daemon:daemon /usr/local/apache2/fcgi-bin/
EOF
}

final_work() {
	buildah copy "$CONTAINER" src/image/httpd.conf /usr/local/apache2/conf/httpd.conf
	buildah copy "$CONTAINER" build/srv/ /usr/local/apache2/htdocs/

	buildah run "$CONTAINER" sh <<"EOF"
chown -R daemon:daemon \
          /var/lib/apache2 \
          /usr/lib/apache2/modules/mod_fcgid.so


mkdir -p /usr/local/apache2/htdocs/images 
chown -R daemon:daemon /usr/local/apache2/htdocs
EOF
}

base() {
	BASE_IMAGE=docker.io/httpd \
		IMAGE_NAME=$BASE_IMAGE_NAME \
		main_flow base_work
}

texture_generator() {
	BASE_IMAGE=containers-storage:$BASE_IMAGE_NAME \
		IMAGE_NAME=$TEXTURE_GENERATOR_IMAGE_NAME \
		main_flow texture_generator_work
}

final() {
	BASE_IMAGE=containers-storage:$TEXTURE_GENERATOR_IMAGE_NAME \
		IMAGE_NAME=$FINAL_IMAGE_NAME \
		main_flow final_work
}

main_flow() {
	CONTAINER=$(buildah from $BASE_IMAGE)
	"${@}"
	buildah commit "$CONTAINER" "$IMAGE_NAME:$IMAGE_TAG"
}

"${@}"
