apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-spherical-harmonics
  labels:
    app: web-spherical-harmonics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-spherical-harmonics
  template:
    metadata:
      labels:
        app: web-spherical-harmonics
    spec:
      containers:
      - name: web-spherical-harmonics
        image: container-registry.dacodastrack.com/web-spherical-harmonics
        ports:
          - containerPort: 80
        imagePullSecrets:
      - name: container-registry-dacodastrack-com-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web-spherical-harmonics
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: web-spherical-harmonics
