#!/bin/bash

set -euo pipefail

SUBCOMMANDS="serialize deserialize generate print_double check_double print_double_array check_double_array"

subcommands() {
	IFS= read -d '' FORMAT_STRING <<"EOF" || true
<< "%s" << "%s"
EOF

	echo "envsubst SUBCOMMANDS"
	for COMMAND in $SUBCOMMANDS
	do
		printf "$FORMAT_STRING" $COMMAND '\n'
	done | pr -to 24
}

process_arguments() {
	IFS= read -d '' FORMAT_STRING <<"EOF"
if ( strcmp(argv[1], "%s") == 0 ) 
{ 
	return %s(--argc, ++argv); 
}

EOF

	echo "envsubst PROCESS_ARGUMENTS"
	for COMMAND in $SUBCOMMANDS
	do 
		printf "$FORMAT_STRING" $COMMAND $COMMAND
	done | pr -to 8
}

set -a
PROCESS_ARGUMENTS=$( process_arguments )
SUBCOMMANDS=$( subcommands  )

envsubst < main.cpp
